# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: fd-rest-api
    meta.helm.sh/release-namespace: alseacare
  creationTimestamp: "2024-04-15T17:30:46Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: fd-rest-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fd-rest-api
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: fd-rest-api-0.1.0
  name: fd-rest-api
  namespace: alseacare
  resourceVersion: "75528597"
  uid: f3eb28be-23e8-420d-84ef-ed92dad9e3de
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: fd-rest-api
      app.kubernetes.io/name: fd-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-08-05T09:31:08-06:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fd-rest-api
        app.kubernetes.io/name: fd-rest-api
    spec:
      containers:
      - args:
        - ApplicationInsights=b51f6329-fa35-4ecc-8aef-5776448a6a00
        - StorageSettingsConnStr=DefaultEndpointsProtocol=https;AccountName=stgappsettings;AccountKey=yikMknw0wart0YTFS0Y242lQTcxuXs9UjKmWxx9WcGhuyimOisov1VYIT40txiiByy7yn3FfKOg7Ejg4Ld6crg==;EndpointSuffix=core.windows.net
        - MerchantCountry=mx
        - UpdateParamsTableStorage=false
        envFrom:
        - configMapRef:
            name: fd-rest-api-cm
        image: mxdevregistrykubalseacare.azurecr.io/fd-rest-api:latest
        imagePullPolicy: IfNotPresent
        name: fd-rest-api
        ports:
        - containerPort: 5002
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api-docs
            port: http
          initialDelaySeconds: 50
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 30
          terminationGracePeriodSeconds: 60
        readinessProbe:
          httpGet:
            path: /api-docs
            port: http
          initialDelaySeconds: 50
          failureThreshold: 1
          periodSeconds: 40
          timeoutSeconds: 30
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fd-rest-api
      serviceAccountName: fd-rest-api
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-15T17:30:46Z"
    lastUpdateTime: "2024-08-05T15:31:12Z"
    message: ReplicaSet "fd-rest-api-84f4c878" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-08-11T08:18:29Z"
    lastUpdateTime: "2024-08-11T08:18:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
